#mysql 连接配置
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/framework?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456